version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.16-stretch-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npx ng build mapper-integration
      - run:
          name: Lint
          command: npx ng lint mapper-integration
#      - run:
#          name: Test
#          command: npx ng test mapper-integration --no-watch
      - run:
          name: Integration Test
          command: npx ng test mapper-angular --no-watch
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> $HOME/.npmrc
      - run:
          name: Dump .npmrc
          command: cat $HOME/.npmrc
      - run:
          name: Publish
          command: npm run publish:packages

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - hold:
          requires:
            - build
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
